# Generated by Django 4.0.10 on 2023-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foldermodel_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermodel',
            name='level',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foldermodel',
            name='semester',
            field=models.CharField(choices=[('first', 'FIRST'), ('second', 'SECOND')], default='first', max_length=50),
        ),
    ]
