# Generated by Django 4.0.10 on 2023-02-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_foldermodel_level_foldermodel_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
