# Generated by Django 4.0.10 on 2023-02-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pdfmodel_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
