# Generated by Django 4.0.10 on 2023-02-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foldermodel',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='foldermodel',
            old_name='file',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='file',
            new_name='category',
        ),
    ]
